/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DigitalLife3D (https://sketchfab.com/DigitalLife3D)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/model-73a-great-hammerhead-shark-77d52f2b0e084fe7bcefbc86b920f080
title: Model 73A - Great Hammerhead Shark
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { OceanStore } from "../OceanStore";
import { useSphere } from "@react-three/cannon";
import { useFrame } from "@react-three/fiber";
import { Vector3 } from "three";

export default function HammerheadShark({ ...props }) {
  let y = 0;
  let z = [0, 0]; // index 1 현재 값, index 2 상승 폭
  let r = [-1, 0];
  let check = false;
  let straight = false;
  let before = null;
  let cameraTarget = useRef(OceanStore.getState().oceanCameraTarget);

  const rRef = useRef();
  const [pRef, pApi] = useSphere(() => ({
    type: "Kinematic",
    mass: 1,
    args: [1],
    ...props,
  }));

  const { nodes, materials, animations } = useGLTF(
    "/oceans/hammerheadShark/scene.gltf"
  );
  const { actions } = useAnimations(animations, pRef);
  useEffect(() => {
    actions.Action.play();
  });

  useEffect(() => {
    OceanStore.subscribe(
      (state) => (cameraTarget.current = state.oceanCameraTarget),
      (state) => state
    );
  });

  useFrame(({ camera }) => {
    if (rRef.current) {
      const [tX, tY, tZ] = rRef.current.getWorldPosition(new Vector3());
      const [bX, bY, bZ] = pRef.current.getWorldPosition(new Vector3());
      pRef.current.lookAt(tX, tY, tZ);

      if (cameraTarget.current === "망치머리상어") {
        camera.position.set(bX + 150, bY + 330, bZ + 330);
        camera.lookAt(bX, bY, bZ);
      }

      if (!check) {
        check = true;
        const num = Math.floor(Math.random() * 3);
        setTimeout(() => {
          check = false;
        }, 5000);

        if (num === 0) {
          r[1] = 0.003;
          z[1] = -0.001;
          straight = false;
          before = "left";
        } else if (num === 1) {
          r[1] = -0.003;
          z[1] = 0.001;
          straight = false;
          before = "right";
        } else if (num === 2) {
          r[1] = 0;
          z[1] = z[0] > 0 ? -0.001 : z[0] === 0 ? 0 : 0.001;
          straight = true;
        }
      }
      pApi.rotation.set(y, (r[0] += r[1]), (z[0] += z[1]));
      if (!straight && (z[0] > 0.5 || z[0] < -0.5)) {
        z[1] = 0;
        z[0] = z[0] > 0.5 ? 0.49 : -0.49;
      } else if (straight) {
        if (before === "left" && z[0] > -0.01) {
          z[1] = 0;
          z[0] = 0;
        } else if (before === "right" && z[0] < 0.01) {
          z[1] = 0;
          z[0] = 0;
        }
      }
      pApi.velocity.set((tX - bX) / 30, (tY - bY) / 30, (tZ - bZ) / 30);
      if (bX < -1600) pApi.position.set(1590, bY, bZ);
      if (bX > 1600) pApi.position.set(-1590, bY, bZ);
      if (bZ < -1600) pApi.position.set(bX, bY, 1590);
      if (bZ > 1600) pApi.position.set(bX, bY, -1590);
    }
  });

  return (
    <group
      ref={pRef}
      {...props}
      dispose={null}
      onClick={(e) => {
        const { oceanCameraTarget } = OceanStore.getState();
        OceanStore.setState({
          oceanCameraTarget:
            oceanCameraTarget !== "망치머리상어" ? "망치머리상어" : false,
        });
        e.stopPropagation();
      }}>
      <mesh ref={rRef} name="rotation_pos" position={[0, 0, 50]} />
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="bodyframe_44" position={[0, 0.02, 0.06]}>
                <group name="GLTF_created_0">
                  <primitive
                    castShadow
                    object={nodes.GLTF_created_0_rootJoint}
                  />
                  <group name="body_41" />
                  <group name="eyes_42" />
                  <group name="teeth_43" />
                  <skinnedMesh
                    castShadow
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.body_v3}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    castShadow
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials["eye.003"]}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  <skinnedMesh
                    castShadow
                    name="Object_11"
                    geometry={nodes.Object_11.geometry}
                    material={materials.body_v3}
                    skeleton={nodes.Object_11.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/oceans/hammerheadShark/scene.gltf");
