/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Reverse Imagineering (https://sketchfab.com/wesleymjames)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ocean-floor-2-meters-depth-maui-3f67b6d2bc77407abe2b36f982c28370
title: Ocean Floor 2 meters depth, Maui
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function OceanFloor({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/oceans/oceanFloor/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null} receiveShadow>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.model_Material_u1_v1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/oceans/oceanFloor/scene.gltf");
