/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Lassi Kaukonen (https://sketchfab.com/thesidekick)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/used-studded-tyre-543c4830ab544e6a9ff5c322ef824508
title: Used studded tyre
*/

import React, { forwardRef, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useCylinder } from "@react-three/cannon";

export const Wheel = forwardRef(({ radius, leftSide, ...props }, ref) => {
  const { nodes, materials } = useGLTF("/cars/hyundaiCar/Wheel/scene.gltf");
  useCylinder(
    () => ({
      mass: 1,
      type: "Kinematic",
      material: "wheel",
      collisionFilterGroup: 0,
      args: [radius, radius, 1.5, 16],
      ...props,
    }),
    ref
  );
  return (
    <group ref={ref} scale={0.8}>
      <mesh rotation={[0, ((leftSide ? -1 : 1) * Math.PI) / 2, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials.Default_OBJ}
        />
      </mesh>
    </group>
  );
});

useGLTF.preload("/cars/hyundaiCar/Wheel/scene.gltf");
